#!/bin/bash

WEB_URL="https://github.com/kdlucas/byte-unixbench/archive/v5.1.3.tar.gz"
source_dir="byte-unixbench-5.1.3/UnixBench"

install()
{
	cp -af Run $BM_ROOT
	cp -avf pgms $BM_ROOT
	cp -avf testdir $BM_ROOT
	mkdir $BM_ROOT/results
}
